"""empty message

Revision ID: 9a1d5e3ced38
Revises: 5a37cbbc79e7
Create Date: 2021-05-07 17:40:07.052062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1d5e3ced38'
down_revision = '5a37cbbc79e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column(
        'seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('venues', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_talent',
                                      sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('venues', 'seeking_venue')
    # ### end Alembic commands ###
